package com.meyuyw.moviecatalog;

import java.util.ArrayList;

public class DataDrama {
    static ArrayList<Movie> data = new ArrayList<>();

    static String[][] drama ={
            {"Descendants of the Sun (English & literal title)","Shi-Jin (Song Joong-Ki) is the captain of the special forces. He catches a motorcycle thief with Sergeant Major Dae-Young (Jin Goo). The thief is injured during his capture and is sent to the hospital. Dae-Young realises his cellphone was stolen by the thief and goes to the hospital to retrieve his cellphone. In the emergency room, Shi-Jin meets Dr. Mo-Yeon (Song Hye-Kyo) for the first time. He falls in love with her immediately. Mo-Yeon mistakenly assumes Shi-Jin is part of thief's criminal gang. He proves to her that he is a soldier with the help of army doctor Myeong-Joo (Kim Ji-Won). Shi-Jin and Mo-Yeon begin to date, but due to their jobs their dates don't go well. Shi-Jin takes an order to lead his soldiers on a peacekeeping mission to the country of Uruk. Meanwhile, Mo-Yeon becomes upset that she fails to become a professor due to a colleague's privileged background. When Shi-Jin and Mo-Yeon meet again, they talk about their views on life and realise how different they are. Shi-Jin, as a soldier, kills to protect lives and Mo-Yeon, as a doctor, tries to save all lives. They say their goodbyes. Eight months later, Mo-Yeon rebuffs the sexual advances of hospital chairman Suk-Won (Tae In-Ho) and as retribution is assigned to lead a medical team in Uruk. There, Shi-Jin and Mo-Yeon meet again.","16 Episode","February 24 - April 14, 2016",String.valueOf(R.drawable.dots)},
            {"Because It's My First Love (literal title)","Five friends, who are all 20-years-old, leave their home for different reasons and begin to live together. The five friends are Tae-O (Ji Soo), Song-Yi (Jung Chae-Yeon), Do-Hyun (Jin Young), Ga-Rin (Choi Ri) and Hoon (Kang Tae-Oh).","8 Episode","April 18, 2019",String.valueOf(R.drawable.first)},
            {"Beautiful World (literal title)","Park Moo-Jin (Park Hee-Soon) and Kang In-Ha (Choo Ja-Hyun) are a married couple. Park Moo-Jin works as a high school teacher and Kang In-Ha runs a bakery. They enjoy their lives with their children. Their peaceful days soon turn into a hellish experience. Their son, who is in the 3rd grade of middle school, is seriously injured due to school violence. Park Moo-Jin and Kang In-Ha try to reveal the truth. Meanwhile, Oh Jin-Pyo (Oh Man-Seok) and Seo Eun-Joo (Cho Yeo-Jeong) are a married couple. They are both from wealthy families. Oh Jin-Pyo is the chairman of a private school foundation inherited from his family. They have never experienced failure or lacked anything. They have a son who makes trouble. The parents coverup for their son's misbehavior.","Jumlah episode belum diketahui","April 5, 2019 - -",String.valueOf(R.drawable.beautifulworld)},
            {"Don't Fight With Fools Even When You Get Pissed Off (literal title)","Kotaro Tanimura (Yuri Chinen) is 22 years old. He is smart enough to have graduated early with a MBA from the University of Cambridge in England. Afterwards, Kotaro Tanimura returns to Japan. He gets a job at a toy company. Kotaro Tanimura is ambitious and enthusiastic with his work. He must deal with fools and he tries to deal with them without fighting.","Jumlah episode belum diketahui","April 22, 2019 - -",String.valueOf(R.drawable.fools)},
            {"Switched (English title)","Shunpei Kaga (Daiki Shigeoka), Koshiro Mizumoto (Tomohiro Kamiyama) and Ayumi Kohinata (Kaya Kiyohara) have been close friends sine they were children. Koshiro Mizumoto confesses his feelings for popular Ayumi Kohinata and their relationship develops romantically. On the day of their first date, Ayumi Kohinata and her unpopular classmate Zenko Umine (Miu Tomita) suddenly change bodies. Ayumi Kohinata is devastated and nobody believes her, except for Shunpei Kaga. Ayumi Kohinata looks for a way to get her body back.","6 Episode","August 1, 2018",String.valueOf(R.drawable.switches)},
            {"The Ghost Detective (English title) / Today's Private Investigator (literal title)","Lee Da-Il is a private investigator. He was formerly in the military, but a whistleblower case led to his discharge. Jung Yeo-Wool becomes his assistant. She is a fearless woman. They work together to solve a mystery surrounding the death of a younger sibling. They also work together to solve other cases, some involving ghosts.","32 Episode","September 5 - October 31, 2018",String.valueOf(R.drawable.ghost)},
            {"The Beauty Inside","A woman changes her appearance whenever a certain supernatural phenomenon occurs. A man falls in love with this woman. Han Se-Kye (Seo Hyun-Jin) is a top actress. She is known as a troublemaker and the object of many rumors. Her life is a mystery, but, in reality, she suffers from an unusual phenomenon. At a certain point every month, her appearance changes to a different person. She lives one week out of every month with a different appearance. Han Se-Kye meets Seo Do-Jae (Lee Min-Ki). Seo Do-Jae is an executive at an airline company. He seems perfect with an attractive appearance and possessing smarts, but he suffers from an inability to recognize faces. He hides this disability and tries hard to memorize people by their habits and mannerisms. The only person's face that he is able to recognize is Han Se-Kye. By meeting her, his life changes.","16 Episode","October 1 - November 20, 2018",String.valueOf(R.drawable.beauty)},
            {"Where Stars Land (English title) / Fox Bride Star (literal title)","Drama series follows people who work diligently at Incheon International Airport. Lee Soo-Yeon (Lee Je-Hoon) graduated from prestigious KAIST (Korea Advanced Institute of Science and Technology). He begins work at Incheon International Airport and gives himself a goal of six months to get used to working there. Lee Soo-Yeon is a mysterious man who keeps people at a distance. There, he meets Han Yeo-Reum (Chae Soo-Bin). She is a new employee in the passenger service team. She wants to be a perfectionist, but her reality is a little different. She makes a lot of mistakes.","32 Episode"," October 1 - November 26, 2018",String.valueOf(R.drawable.stars)},
            {" The Long Good-bye (English title)","Bae Sang-Hee (Lim Ju-Hwan) is a novelist. He is having a hard time finishing his second novel. His long time girlfriend is Jung Yi-Na (Jang Hee-Jin). She works as an editor for a publishing company. Bae Sang-Hee agonizes over his work and his love life.","1 Episode","October 19, 2018",String.valueOf(R.drawable.goodbye)},
            {"Feel Good To Die (English title) / Happy If You Died (literal title)","Lee Roo-Da (Baek Jin-Hee) tries to reform her boss Baek Jin-Sang (Kang Ji-Hwan) to become a better person and a better boss. Baek Jin-Sang is Lee Roo-Da’s boss and he works as a team leader of a company. The team members, including Lee Roo-Da, do not like him at all. He is mean and arrogant to the employees. He always believes he is right. On the night of November 7th, Lee Roo-Da has a dream of her boss being hit by a truck. The next morning she wakes up and finds that it is still November 7th.","32 Episode","November 7 - December 27, 2018",String.valueOf(R.drawable.die)}
    };

    public static ArrayList<Movie> getData() {
            for (String[] var : drama) {
                Movie d = new Movie();
                d.setTitle(var[0]);
                d.setOverview(var[1]);
                d.setRuntime(var[2]);
                d.setRelease(var[3]);
                d.setPoster(Integer.valueOf(var[4]));
                data.add(d);
            }
            return data;
    }
}
